### PR TITLE
ENH: Add support for recording vtkMRMLVolumePropertyNode

### PR DESCRIPTION
**Pull request by jcfr**
This allows to save transfer functions updates associated with volume rendering.

### CODE REVIEW

**Comment by jcfr** [comment]
@pieper This is exciting, these few lines allow to play sequence where transfer functions are updated. :tada:

**Comment by pieper** [comment]
Very cool!

**Review by lassoan — APPROVED** [review]
Looks good! Thanks for this and all the other pull requests. For Slicer5, we should make these methods part of the MRML node API, so that we don't need to add these methods to an external class. But probably we can wait a month or so to see what API we need for interpolation and update the MRML node API then.

**Comment by jcfr** [comment]
> we should make these methods part of the MRML node API, so that we don't need to add these methods to an external class

That would make sense, do we need to make the copy API consistent between all nodes first ? See https://www.slicer.org/wiki/Documentation/Labs/Slicer5-roadmap#Revisit_MRML_Copy_API

>  But probably we can wait a month or so to see what API we need for interpolation

Indeed, for now adding the sequencer node or event registering it from an extension is quite easy.

**Pull request merged**
