### PR TITLE
ENH: Add ability to specify the number of decimals in the sequence br…

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
…owser playback widget

re #67

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
image

**Comment by lassoan** [comment]
I would prefer a format string, as it allows many more options and could handle changing number of non-decimal digits (1.11 takes less space than 111111.11).

Another issue is that default font is not fixed size, so 1.111 would take less space than 5.555. Therefore, even with fixed number of decimals, the field size could change slightly.

So, I think we cannot avoid setting fixed size for the label (computed from font metrics or text rendering tests; or checking size of widget and prevent size reduction - only allow the label to grow).

**Comment by Sunderlandkyl** [comment]
Yeah, I initially tested a format string, but I found that it was easy to enter an invalid format that could cause a crash when using sprintf.

If there's a more reliable function in VTK or wherever, I can switch back easily to that approach.

**Comment by lassoan** [comment]
Format string is already used in Colors module / Scalar bar / Labels properties / Format.

A regex check is done and if the label format is invalid then some default format is used - see vtkSlicerScalarBarActor::LayoutTicks().

We could factor out this logic into a helper function in vtkAddon and use that in vtkSlicerScalarBarActor and in Sequences.

If needed, the regexp can be improved in the future.

**Pull request merged**
