### PR TITLE
Allowing other extensions to depend on Sequences.

### PR DESCRIPTION
**Pull request by matthewsholden**
In particular, updates allowing sequencing of the double array node make it so that Perk Tutor can depend on Sequences.

### CODE REVIEW

**Comment by lassoan** [comment]
I don't think any changes are needed to depend on Sequences. If you specify for PerkTutor that id depends on Sequences then the factory computer will provide Sequences extension directory for PerkTutor.
Did you follow some examples or templates to implement this dependency management code?

**Comment by jcfr** [comment]
This changes allows to leverage the fact `Sequences_DIR` is passed to your dependent extension. 

It is usually needed to leverage dependency not already managed by Slicer. For example:

https://github.com/SBU-BMI/SlicerOpenCV/blob/bbaeb786cd42734a3fd5b783be3038540cd203a8/CMakeLists.txt#L54-L73

@mholden8  Which use case was causing you trouble ?

as a side note, I like the idea of having Config file available in extension .. this is going toward the direction of Slicer and extension SDK ... but we need to experiment and find out a solution that will scale.

**Comment by matthewsholden** [comment]
Thanks for the input. I was indeed trying to follow the OpenCV example above.

The difficulty that I'm running into is that `Sequences_DIR` is the directory where the binaries are built, but doesn't give us any information on where the header files are. I tried to add the SequencesConfig.cmake file to allow the header files directory to be passed to other extensions.

If I don't pass the header file directories to Perk Tutor, I get the following build errors:

`
Error	1	error C1083: Cannot open include file: 'vtkMRMLSequenceNode.h': No such file or directory	d:\perktutor\perktutordepends\workflowsegmentation\mrml\vtkMarkovModel.h	24	1	vtkSlicerWorkflowSegmentationModuleMRML
Error	2	error C1083: Cannot open include file: 'vtkMRMLSequenceNode.h': No such file or directory	d:\perktutor\perktutordepends\workflowsegmentation\mrml\vtkMarkovModel.h	24	1	vtkSlicerWorkflowSegmentationModuleMRML
Error	3	error C1083: Cannot open include file: 'vtkMRMLSequenceNode.h': No such file or directory	d:\perktutor\perktutordepends\transformrecorder\logic\vtkSlicerTransformRecorderLogic.h	37	1	vtkSlicerTransformRecorderModuleLogic
Error	4	error C1083: Cannot open include file: 'vtkMRMLSequenceNode.h': No such file or directory	d:\perktutor\perktutordepends\workflowsegmentation\mrml\vtkMRMLWorkflowSequenceNode.h	30	1	vtkSlicerWorkflowSegmentationModuleMRML
Error	5	error C1083: Cannot open include file: 'vtkMRMLSequenceNode.h': No such file or directory	d:\perktutor\perktutordepends\workflowsegmentation\mrml\vtkMRMLWorkflowSequenceNode.h	30	1	vtkSlicerWorkflowSegmentationModuleMRML
Error	6	error C1083: Cannot open include file: 'vtkMRMLSequenceBrowserNode.h': No such file or directory	d:\perktutor\perktutordepends\perkevaluator\mrml\vtkMRMLPerkEvaluatorNode.h	45	1	vtkSlicerPerkEvaluatorModuleMRML
`
etc...

I spoke with @lassoan this morning about this. We discussed that exporting targets from the Sequences extension with the appropriate properties (i.e. the include directories) would be a better solution.

@jcfr Do you agree? And do you have any suggestions on how to best go about doing this?

**Comment by matthewsholden** [comment]
@lassoan is this what you had in mind: https://github.com/mholden8/Sequences/commit/9e6c1212275434e2408fe971508e4a2c0dffcce2?

For each VTK/Qt library in the module (e.g. vtkSlicerSequencesModuleMRML, qSlicerSequencesModuleWidget, etc.) this creates a Target.cmake file. The Target,cmake files can be used by extensions depending on Sequences to automatically locate the library and header files.

**Comment by lassoan** [comment]
@jcfr What do you recommend: should we implement a one-off solution in Sequences extension to allow loadable modules in other extensions use it, or this should be handled centrally for all extensions?

**Comment by matthewsholden** [comment]
Thanks for the input.

Superseded by the pull request: Slicer/Slicer#707.

**Pull request closed without merging**
